import test from 'node:test';
import assert from 'node:assert/strict';
import { ResearchKernel } from '../services/research-kernel.ts';

test('synthetic multi-company corpus surfaces an evidence-backed shared pattern', () => {
  const kernel = new ResearchKernel(); const alpha = kernel.createCompany({ legalName: 'Alpha Retail Inc.', ticker: 'ALPH' }); const beta = kernel.createCompany({ legalName: 'Beta Commerce Inc.', ticker: 'BETA' }); const first = kernel.ingestText({ providerId: 'synthetic-evaluation', sourceType: 'SYNTHETIC_FIXTURE', tier: 'PRIMARY', title: 'Alpha synthetic filing', companyId: alpha.id, text: 'Synthetic Alpha commentary cites elevated customer acquisition costs and lower marketing efficiency.', metadata: { synthetic: true, signalTags: ['customer acquisition pressure'] } }); const second = kernel.ingestText({ providerId: 'synthetic-evaluation', sourceType: 'SYNTHETIC_FIXTURE', tier: 'PRIMARY', title: 'Beta synthetic filing', companyId: beta.id, text: 'Synthetic Beta commentary cites elevated customer acquisition costs and lower marketing efficiency.', metadata: { synthetic: true, signalTags: ['customer acquisition pressure'] } });
  const [pattern] = kernel.discoverCrossCompanyPatterns(); assert.equal(pattern.type, 'PATTERN'); assert.deepEqual(new Set(pattern.companyIds), new Set([alpha.id, beta.id])); assert.deepEqual(new Set(pattern.sourceIds), new Set([first.id, second.id])); const theme = kernel.createTheme({ name: 'Customer acquisition pressure', description: 'Synthetic cross-company theme.' }); kernel.reviewDiscoveryCandidate(pattern.id, 'ACCEPTED', theme.id); const detail = kernel.themeDetail(theme.id); assert.equal(detail.metrics.breadth, 2); assert.equal(detail.candidates[0].status, 'ACCEPTED');
});
test('contradiction analytics surfaces both claims and evidence instead of averaging them away', () => {
  const kernel = new ResearchKernel(); const source = kernel.ingestText({ providerId: 'synthetic-evaluation', sourceType: 'SYNTHETIC_FIXTURE', tier: 'PRIMARY', title: 'Synthetic disagreement', text: 'Synthetic supplier commentary reports expanding demand. Synthetic customer commentary reports declining demand.', metadata: { synthetic: true } }); const observations = kernel.extractObservations(source.id); const supplier = kernel.proposeClaim(observations[0].id); const customer = kernel.proposeClaim(observations[1].id); kernel.linkEvidence({ claimId: supplier.id, observationId: observations[0].id, sourceId: source.id, direction: 'SUPPORTS' }); kernel.linkEvidence({ claimId: customer.id, observationId: observations[1].id, sourceId: source.id, direction: 'SUPPORTS' }); kernel.recordContradiction({ claimAId: supplier.id, claimBId: customer.id, description: 'Synthetic supplier/customer demand disagreement.' }); const [candidate] = kernel.surfaceContradictions(); assert.equal(candidate.type, 'CONTRADICTION'); assert.deepEqual(new Set(candidate.claimIds), new Set([supplier.id, customer.id])); assert.ok(candidate.evidenceIds.length >= 2);
});
