import test from 'node:test';
import assert from 'node:assert/strict';
import { ResearchKernel } from '../services/research-kernel.ts';

test('thesis revisions preserve history and report what changed', () => {
  const kernel = new ResearchKernel(); const hypothesis = kernel.createHypothesis({ statement: 'Private lending demand may increase.', status: 'TESTING', entityIds: [], themeIds: [], confidence: 0.4 }); const question = kernel.createQuestion({ question: 'How large is the funding gap?', importance: 1, uncertainty: 0.9, thesisImpact: 0.9 }); const thesis = kernel.createThesis({ title: 'Synthetic SLM opportunity', summary: 'Evidence is insufficient for a conclusion.', confidence: 0.3, hypothesisIds: [hypothesis.id], questionIds: [question.id] }); const revised = kernel.reviseThesis(thesis.id, { summary: 'New synthetic evidence supports a narrower opportunity, but underwriting remains unresolved.', confidence: 0.45, status: 'STRENGTHENING' }); const detail = kernel.thesisDetail(thesis.id);
  assert.equal(detail.revisions.length, 2); assert.equal(detail.revisions[0].confidence, 0.3); assert.match(revised.changeSummary, /increased/); assert.equal(detail.thesis.currentRevisionId, revised.id);
});
test('conditions, risks, catalysts, forecasts, and contradictions remain structured', () => {
  const kernel = new ResearchKernel(); const source = kernel.ingestText({ providerId: 'fixture', sourceType: 'SYNTHETIC', tier: 'PRIMARY', title: 'Fixture', text: 'Synthetic document contains enough prose for a first direct observation in a structured evaluation. A second synthetic statement deliberately disagrees with the first for contradiction testing.' }); const observations = kernel.extractObservations(source.id); const a = kernel.proposeClaim(observations[0].id); const b = kernel.proposeClaim(observations[1].id); const thesis = kernel.createThesis({ title: 'Structured thesis', summary: 'Synthetic only.', confidence: 0.2 }); kernel.addCondition({ thesisId: thesis.id, type: 'KILL', statement: 'Credit losses exceed the modeled range.' }); kernel.addRisk({ thesisId: thesis.id, statement: 'Demand does not convert to originations.', likelihood: 0.5, impact: 0.8 }); kernel.addCatalyst({ thesisId: thesis.id, statement: 'Policy implementation guidance.' }); kernel.addForecast({ thesisId: thesis.id, metric: 'Incremental originations', period: 'FY2027', value: 0, unit: 'USD', assumptions: ['Synthetic placeholder, not an investment estimate.'] }); kernel.recordContradiction({ thesisId: thesis.id, claimAId: a.id, claimBId: b.id, description: 'Synthetic conflicting commentary.' }); const detail = kernel.thesisDetail(thesis.id); assert.equal(detail.conditions.length, 1); assert.equal(detail.risks.length, 1); assert.equal(detail.catalysts.length, 1); assert.equal(detail.forecasts.length, 1); assert.equal(detail.contradictions.length, 1);
});
