import readline from 'node:readline';
import { ResearchKernel } from '../services/research-kernel.ts';

const kernel = new ResearchKernel(); await kernel.load();
const tools = [
  { name: 'research_list_sources', description: 'List immutable research sources.', inputSchema: { type: 'object', properties: {} } },
  { name: 'research_get_claim_lineage', description: 'Return a claim with its evidence, observations, and sources.', inputSchema: { type: 'object', properties: { claimId: { type: 'string' } }, required: ['claimId'] } },
  { name: 'research_create_question', description: 'Create a persistent research question.', inputSchema: { type: 'object', properties: { question: { type: 'string' }, importance: { type: 'number' }, uncertainty: { type: 'number' }, thesisImpact: { type: 'number' } }, required: ['question', 'importance', 'uncertainty', 'thesisImpact'] } },
  { name: 'research_list_theses', description: 'List current thesis state.', inputSchema: { type: 'object', properties: {} } },
  { name: 'research_get_thesis', description: 'Return thesis revisions, conditions, risks, catalysts, forecasts, and contradictions.', inputSchema: { type: 'object', properties: { thesisId: { type: 'string' } }, required: ['thesisId'] } },
  { name: 'research_create_thesis', description: 'Create an initial immutable thesis revision.', inputSchema: { type: 'object', properties: { title: { type: 'string' }, summary: { type: 'string' }, confidence: { type: 'number' } }, required: ['title', 'summary', 'confidence'] } },
  { name: 'research_revise_thesis', description: 'Create a new thesis revision; prior revisions remain available.', inputSchema: { type: 'object', properties: { thesisId: { type: 'string' }, summary: { type: 'string' }, confidence: { type: 'number' }, status: { type: 'string' } }, required: ['thesisId', 'summary', 'confidence', 'status'] } },
  { name: 'research_list_discovery_inbox', description: 'List evidence-backed discovery signals and patterns awaiting review.', inputSchema: { type: 'object', properties: {} } },
  { name: 'research_synthesize_cross_company_patterns', description: 'Surface repeated source tags across two or more companies.', inputSchema: { type: 'object', properties: {} } },
  { name: 'research_get_theme', description: 'Return a theme, breadth, acceleration, candidates, events, and relationships.', inputSchema: { type: 'object', properties: { themeId: { type: 'string' } }, required: ['themeId'] } },
];
const reply = (id: unknown, result: unknown) => process.stdout.write(`${JSON.stringify({ jsonrpc: '2.0', id, result })}\n`);
readline.createInterface({ input: process.stdin }).on('line', async (line) => { try { const request = JSON.parse(line); if (request.method === 'tools/list') return reply(request.id, { tools }); if (request.method === 'tools/call') { const args = request.params.arguments ?? {}; let value: unknown; if (request.params.name === 'research_list_sources') value = kernel.snapshot().sources; else if (request.params.name === 'research_get_claim_lineage') value = kernel.lineage(args.claimId); else if (request.params.name === 'research_create_question') value = kernel.createQuestion(args); else if (request.params.name === 'research_list_theses') value = kernel.snapshot().theses; else if (request.params.name === 'research_get_thesis') value = kernel.thesisDetail(args.thesisId); else if (request.params.name === 'research_create_thesis') value = kernel.createThesis(args); else if (request.params.name === 'research_revise_thesis') value = kernel.reviseThesis(args.thesisId, args); else if (request.params.name === 'research_list_discovery_inbox') value = kernel.discoveryInbox(); else if (request.params.name === 'research_synthesize_cross_company_patterns') value = kernel.discoverCrossCompanyPatterns(); else if (request.params.name === 'research_get_theme') value = kernel.themeDetail(args.themeId); else throw new Error('Unknown MCP tool'); if (request.params.name.startsWith('research_create') || request.params.name === 'research_revise_thesis' || request.params.name === 'research_synthesize_cross_company_patterns') await kernel.save(); return reply(request.id, { content: [{ type: 'text', text: JSON.stringify(value, null, 2) }] }); } reply(request.id, { protocolVersion: '2024-11-05', capabilities: { tools: {} }, serverInfo: { name: 'analystos', version: '0.3.0' } }); } catch (error) { reply(null, { isError: true, content: [{ type: 'text', text: String(error) }] }); } });
